# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/skillhelper',
                'doc_host': 'https://LA3D.github.io',
                'git_url': 'https://github.com/LA3D/skillhelper',
                'lib_path': 'skillhelper'},
  'syms': {'skillhelper.core': {'skillhelper.core.foo': ('core.html#foo', 'skillhelper/core.py')}}}
