"""Agent Building Block that uses skills"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_skilledagent.ipynb.

# %% auto 0
__all__ = ['SkilledAgent']

# %% ../nbs/01_skilledagent.ipynb 3
from claudette import *

# %% ../nbs/01_skilledagent.ipynb 4
from .core import *
from .core import SecurityPolicy, validate_capabilities

# %% ../nbs/01_skilledagent.ipynb 7
from fastcore import *
from fastcore.basics import AttrDict
import strictyaml
from fastcore.xtras import *
from fastcore.basics import first
from pathlib import Path
from dataclasses import dataclass
from typing import Optional
from fastcore.basics import patch
from safecmd import safe_run
import ast
import os

# %% ../nbs/01_skilledagent.ipynb 10
class SkilledAgent:
    "Extend claudette/lisette agent with Agent Skills"
    def __init__(self, agent, policy=None): self.agent,self.policy,self.active_skills = agent,policy,{}

# %% ../nbs/01_skilledagent.ipynb 13
@patch
def list_skills(self:SkilledAgent): return discover_all()

# %% ../nbs/01_skilledagent.ipynb 17
@patch
def activate_skill(self:SkilledAgent, name:str):
    skill = first(s for s in discover_all() if s.name==name)
    if not skill: return AttrDict(success=False, skill=None, error=f"Skill '{name}' not found")
    
    # Security validation
    if self.policy:
        try: validate_capabilities(skill, self.policy)
        except ValueError as e: return AttrDict(success=False, skill=None, error=str(e))
    
    self.active_skills[name] = skill
    for t in skill.get_tools().values(): self.agent.tools.append(t)
    self.agent.h.append({'role': 'user', 'content': f"[Skill activated: {name}]\n\n{skill.instructions}"})
    return AttrDict(success=True, skill=skill, error=None)

# %% ../nbs/01_skilledagent.ipynb 25
@patch
def _skills_summary(self:SkilledAgent):
    "Return formatted skills metadata for system prompt"
    skills = discover_all()
    if not skills: return ""
    lines = ["## Available Skills", ""]
    for s in skills:
        lines.append(f"- **{s.name}**: {s.description}")
    return "\n".join(lines)

# %% ../nbs/01_skilledagent.ipynb 26
@patch
def update_sp(self:SkilledAgent):
    "Append skills summary to agent's system prompt"
    summary = self._skills_summary()
    if not summary: return
    base = self.agent.sp or ""
    self.agent.sp = f"{base}\n\n{summary}" if base else summary
